#! /usr/bin/env bash

# check if atleast one arguement is provied


if [ -z "$1" ]; then
    echo "There needs to be a bucket name"
    exit 1
fi

BUCKET_NAME="$1"

aws s3api delete-bucket \
  --bucket "$BUCKET_NAME" \
  --query 'Location' \
  --output text
